apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 4m
spec:
  rules:
  - host: api
    http:
      paths:
      - backend:
          serviceName: api-service
          servicePort: 80
