apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
      role: web
  template:
    metadata:
      labels:
        app: api
        role: web
    spec:
      imagePullSecrets:
      - name: gitlab-registry
      containers:
      - image: registry.gitlab.com/openculinary/api
        imagePullPolicy: IfNotPresent
        name: api
        ports:
        - containerPort: 80
        env:
          - name: MAIL_USERNAME
            valueFrom:
              secretKeyRef:
                name: api-verifications-mail
                key: username
          - name: MAIL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: api-verifications-mail
                key: password
  replicas: 3
