apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-worker-deployment
spec:
  template:
    metadata:
      labels:
        app: api-worker
    spec:
      imagePullSecrets:
      - name: gitlab-registry
      containers:
      - image: registry.gitlab.com/openculinary/api
        imagePullPolicy: IfNotPresent
        name: api
        command: ['pipenv']
        args: ['run', 'celery', 'worker', '-A', 'reciperadar.workers', '-Q', 'celery,crawl_recipe,process_recipe,index_recipe']
  replicas: 5
  selector:
    matchLabels:
      app: api-worker
